[[redirects]]
  from = "/api/*"
  to = "https://hotel-mongodbv2-3.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[build]
  command = "npm run build"
  publish = ".next"
  
[build.environment]
  NEXT_PUBLIC_API_URL = "https://hotel-mongodbv2-3.onrender.com/api"
  NEXT_PUBLIC_URL = "https://hotel-mongodbv2-3.onrender.com"
